### ISSUE TITLE
Session graph Error when Running "test.py"

### ISSUE THREAD

**Issue by iamweiweishi** [ANRGUSC/DEFER#3]
Hi,
I am trying to reproduce the results following your guidance.

First, I run 'local_infer.py', everything works well and the code downloads an "resnet*.h5".

Then, I set computeNodes as [ip1, ip2]. I also modified part_at as ["conv3_block1_add"].

I run 'node.py' in ip2 node. And finnaly I run "test.py" in ip1 node.

But I met some problem:

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/anaconda3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/anaconda3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "../src/dispatcher.py", line 118, in run_defer
    self._dispatchModels(models_to_dispatch, self.computeNodes)
  File "../src/dispatcher.py", line 61, in _dispatchModels
    print("getting weights: ", models[i].get_weights())
  File "/home/anaconda3.6/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 173, in get_weights
    return super(Model, self).get_weights()
  File "/home/anaconda3.6/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 1352, in get_weights
    return backend.batch_get_value(params)
  File "/home/anaconda3.6/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3185, in batch_get_value
    return get_session(tensors).run(tensors)
  File "/home/anaconda3.6/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/anaconda3.6/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1105, in _run
    raise RuntimeError('The Session graph is empty.  Add operations to the '
RuntimeError: The Session graph is empty.  Add operations to the graph before calling run().`

It seems like the  tensorflow version might cause the issue. I am using tf-1.15.0. 

May I know which tf-version you are using? Or did I make some mistakes during the experiments?

Many thanks.

**Comment by ArjunParthasarathy** [comment]
I used tf-1.5.0, and Python 3.6.x should be fine. You could try `g = tf.get_default_graph()` and using `with g.as_default():` where you make the call to DEFER. However, I suspect that the versioning is the issue and tf-1.5.0 should work, so try changing the version first. Let me know if you still encounter issues.

Thanks.

**Comment by luotong1997** [comment]
Hi,

When I tried to follow, I was confused about the content of “For each model, we varied the number of compute nodes between 4, 6, and 8. This was done using the CORE Network Emulator (http://coreemu.github.io/core), which allowed us to create network topologies simulating these
different node configurations and run the simulation locally in a close-to-zero latency environment.”  in your paper. Do I need to download the CORE Network Simulator on a Linux system and simulate computing nodes on it for experimentation? I tried using the server in the laboratory as the main node and my desktop as the computing node. However, even if the server and desktop can establish communication and the IP parameters in the code are correct, the program still cannot run.

I would greatly appreciate it if you could provide an answer.

**Comment by ArjunParthasarathy** [comment]
Hi,

Yes you should download the CORE Network Emulator and create simulated nodes. You would run the dispatcher on one node and the compute nodes on the other simulated nodes.
